import { contactData } from "@/data/contact-data";
import { linkData } from "@/data/link-data";
import Link from "next/link";

export default function PrivacyPolicy() {
  return (
    <div className="bg-white py-16 relative mt-[98px]">
      <div className="w-full max-w-7xl px-8 md:px-16 mx-auto">
        <div className="w-full justify-start items-center gap-10 grid grid-cols-1">
          <div className="w-full flex-col justify-start items-center gap-10 inline-flex">
            <div className="w-full flex-col justify-start lg:items-start gap-4 flex">
              <h2 className="text-[#4B5945] text-4xl font-bold font-manrope leading-normal text-start ">
                Privacy Policy
              </h2>
              <p className="text-gray-500 text-base font-normal leading-relaxed max-w-7xl">
                Effective date: 1 January, 2024
              </p>
            </div>
          </div>
          <p className="text-gray-700 text-base font-normal leading-relaxed lg:text-start max-w-7xl mx-auto">
            10169392 Manitoba Ltd. (H Plus Day Spa ) (“us”, “we”, or “our”)
            operates the{" "}
            <Link
              href={linkData.domain_link}
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#4B5945] underline"
            >
              {linkData.domain_link}
            </Link>{" "}
            website (hereinafter referred to as the “Service”). This page
            informs you of our policies regarding the collection, use and
            disclosure of personal data when you use our Service and the choices
            you have associated with that data. We use your data to provide and
            improve the Service. By using the Service, you agree to the
            collection and use of information in accordance with this policy.
          </p>
          <h3 className="-mt-2 -mb-2 text-[#4B5945] text-2xl font-semibold">
            Definitions
          </h3>
          <ul className="space-y-6 list-disc ml-4 text-gray-700">
            <li>
              <strong>Service:</strong> Service is the{" "}
              <Link
                href={linkData.domain_link}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#4B5945] underline"
              >
                {linkData.domain_link}
              </Link>{" "}
              website operated by 10169392 Manitoba Ltd. (H Plus Day Spa Massage
              & Spa).
            </li>
            <li>
              <strong>Personal Data:</strong> Data about a living individual who
              can be identified from those data (or from those and other
              information either in our possession or likely to come into our
              possession).
            </li>
            <li>
              <strong>Usage Data:</strong> Data collected automatically either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              <strong>Cookies:</strong> Small files stored on your device
              (computer or mobile device).
            </li>
          </ul>
          <h3 className="-mt-2 -mb-2 text-[#4B5945] text-2xl font-semibold">
            Information Collection and Use
          </h3>
          <p className="text-gray-700">
            We collect several different types of information for various
            purposes to provide and improve our Service to you.
          </p>
          <h4 className="-mt-4 -mb-4 text-[#4B5945] text-xl font-semibold">
            Types of Data Collected
          </h4>
          <div className="text-gray-700">
            <div className="font-semibold">Personal Data</div> While using our
            Service, we may ask you to provide us with certain personally
            identifiable information that can be used to contact or identify you
            (“Personal Data”). Personally identifiable information may include,
            but is not limited to:{" "}
          </div>
          <ul className="space-y-4 list-disc ml-4 -mt-6 -mb-6 text-gray-700">
            <li>Email address</li>
            <li>First name and last names</li>
            <li>Phone number</li>
            <li>Cookies and Usage Data</li>
          </ul>
          <div className="text-gray-700">
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link or
            the instructions provided in any email we send.
          </div>
          <div className="text-gray-700">
            <div className="text-gray-700 font-semibold -mt-4">Usage Data</div>{" "}
            used (“Usage Data”). This Usage Data may include information such as
            your computer’s Internet Protocol address (e.g. IP address), browser
            type, browser version, the pages of our Service that you visit, the
            time and date of your visit, the time spent on those pages, unique
            device identifiers and other diagnostic data. <br />
            <br />
            <div className="text-gray-700">
              Tracking & Cookies Data; We use cookies and similar tracking
              technologies to track the activity on our Service and we hold
              certain information. Cookies are files with a small amount of data
              which may include an anonymous unique identifier. Cookies are sent
              to your browser from a website and stored on your device. Other
              tracking technologies are also used such as beacons, tags and
              scripts to collect and track information and to improve and
              analyse our Service. You can instruct your browser to refuse all
              cookies or to indicate when a cookie is being sent. However, if
              you do not accept cookies, you may not be able to use some
              portions of our Service.
            </div>
            <br />
            <br />
            <div className="text-gray-700">
              You can instruct your browser to refuse all cookies or to indicate
              when a cookie is being sent. However, if you do not accept
              cookies, you may not be able to use some portions of our Service.
            </div>
          </div>
          <h4 className="-mt-4 -mb-4 text-[#4B5945] text-xl font-semibold">
            Use of Data
          </h4>
          <p className="text-gray-700">
            We collect several different types of information for various
            purposes to provide and improve our Service to you. 10169392
            Manitoba Ltd. (H Plus Day Spa ) uses the collected data for various
            purposes:
          </p>
          <ul className="space-y-4 list-disc ml-4 -mt-6 text-gray-700">
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>
              To allow you to participate in interactive features of our Service
              when you choose to do so
            </li>
            <li>To provide customer support</li>
            <li>
              To gather analysis or valuable information so that we can improve
              our Service
            </li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>
              To provide you with news, special offers and general information
              about other goods, services and events which we offer that are
              similar to those that you have already purchased or enquired about
              unless you have opted not to receive such information
            </li>
          </ul>
          <h4 className="-mb-4 -mt-4 text-[#4B5945] text-xl font-semibold">
            Transfer of Data
          </h4>
          <p className="text-gray-700">
            Your information, including Personal Data, may be transferred to —
            and maintained on — computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction. <br />
            <br /> If you are located outside Canada and choose to provide
            information to us, please note that we transfer the data, including
            Personal Data, to Canada and process it there. <br />
            <br />
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
            10169392 Manitoba Ltd. (H Plus Day Spa ) will take all the steps
            reasonably necessary to ensure that your data is treated securely
            and in accordance with this Privacy Policy and no transfer of your
            Personal Data will take place to an organization or a country unless
            there are adequate controls in place including the security of your
            data and other personal information.
          </p>
          <h3 className="-mt-2 -mb-2 text-[#4B5945] text-2xl font-semibold">
            Disclosure of Data Legal Requirements
          </h3>
          <p className="text-gray-700">
            10169392 Manitoba Ltd. (H Plus Day Spa ) may disclose your Personal
            Data in the good faith belief that such action is necessary to:
          </p>
          <ul className="space-y-4 list-disc ml-4 -mt-6 text-gray-700">
            <li>To comply with a legal obligation</li>
            <li>
              To protect and defend the rights or property of 10169392 Manitoba
              Ltd. (H Plus Day Spa )
            </li>
            <li>
              To prevent or investigate possible wrongdoing in connection with
              the Service
            </li>
            <li>
              To protect the personal safety of users of the Service or the
              public
            </li>
            <li>To protect against legal liability</li>
          </ul>
          <h3 className="-mt-2 -mb-2 text-[#4B5945] text-2xl font-semibold">
            Service Providers
          </h3>
          <p className="text-gray-700">
            We may employ third party companies and individuals to facilitate
            our Service (“Service Providers”), provide the Service on our
            behalf, perform Service-related services or assist us in analyzing
            how our Service is used. These third parties have access to your
            Personal Data only to perform these tasks on our behalf and are
            obligated not to disclose or use it for any other purpose.
          </p>
          <h3 className="-mt-2 -mb-2 text-[#4B5945] text-2xl font-semibold">
            Payments
          </h3>
          <p className="text-gray-700">
            We may provide paid products and/or services within the Service. In
            that case, we use third-party services for payment processing (e.g.
            payment processors). <br />
            <br />
            We will not store or collect your payment card details. That
            information is provided directly to our third-party payment
            processors whose use of your personal information is governed by
            their Privacy Policy. These payment processors adhere to the
            standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa, MasterCard,
            American Express and Discover. PCI-DSS requirements help ensure the
            secure handling of payment information. <br />
            <br /> The payment processors we work with are: ChaseTheir Privacy
            Policy can be viewed at{" "}
            <Link
              href="https://www.chase.com/digital/resources/privacy-security/privacy/online-privacy-policy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#4B5945] underline"
            >
              https://www.chase.com/digital/resources/privacy-security/privacy/online-privacy-policy
            </Link>{" "}
          </p>
          <h3 className="-mt-2 -mb-2 text-[#4B5945] text-2xl font-semibold">
            Links to Other Sites
          </h3>
          <p className="text-gray-700">
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party’s site. We strongly advise you to review the Privacy
            Policy of every site you visit.
            <br />
            <br />
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
          <h3 className="-mt-2 -mb-2 text-[#4B5945] text-2xl font-semibold">
            Changes to This Privacy Policy
          </h3>
          <p className="text-gray-700">
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update the
            “effective date” at the top of this Privacy Policy.
            <br />
            <br />
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
          <h3 className="-mt-2 -mb-2 text-[#4B5945] text-2xl font-semibold">
            Contact Us
          </h3>
          <p className="text-gray-700">
            If you have any questions about this Privacy Policy, please contact
            us by email:{" "}
            <Link
              href={contactData.email_link}
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#4B5945] underline"
            >
              {contactData.email}
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
